steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "gsm_secret: $(gcloud beta secrets versions access --secret=my-secret latest)" > /workspace/my-secret-file.txt
        cat /workspace/my-secret-file.txt