steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "$(gcloud beta secrets versions access --secret=my-secret latest)" > /workspace/my-secret-file.txt
        ls
        echo -e "\n"
        cat my-secret-file.txt